version: 2

jobs:
  image:
    docker:
      - image: circleci/golang:1.11.5
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build
               -t ${DOCKER_LOGIN}/crane:latest
               .docker
      - run: > 
          [ ${CIRCLE_TAG} ] && docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD} || true
      - run: >
          [ ${CIRCLE_TAG} ] && docker tag ${DOCKER_LOGIN}/crane:latest ${DOCKER_LOGIN}/crane:${CIRCLE_TAG} || true
      - run: > 
          [ ${CIRCLE_TAG} ] && docker push ${DOCKER_LOGIN}/crane:latest || true
      - run: >
          [ ${CIRCLE_TAG} ] && docker push ${DOCKER_LOGIN}/crane:${CIRCLE_TAG} || true

  binary:
    docker:
      - image: circleci/golang:1.11.5
    steps:
      - checkout
      - run: sudo apt-get install musl-tools 
      - run: go get github.com/tcnksm/ghr
      - run: CC=musl-gcc go build --ldflags "-X main.DefaultRepo=$DOCKER_LOGIN -X main.DefaultTag=${CIRCLE_TAG:-latest} -s -w -linkmode external -extldflags '-static'" -o /tmp/crane
      - run: > 
          [ ${CIRCLE_TAG} ] && ghr ${CIRCLE_TAG} /tmp/crane || true
      - store_artifacts:
          path: /tmp/crane

workflows:
  version: 2
  build:
    jobs:
      - image:
          filters:
            tags:
              only: /^v.*/
      - binary:
          filters:
            tags:
              only: /^v.*/

